### ISSUE TITLE
sugestie

### ISSUE THREAD

**Issue by bruhmoment21** [cristeigabriel/compiletime-string-to-bytearray#1]
exemplu: daca sunt 4 "?" unul dupa altul sa puna -4 ca sa nu fie -1, -1, -1, -1.

**Comment by cristeigabriel** [comment]
? e wildcard sa puna -1 deoarece este implicit unknown info si trebuie handled manual

**Comment by cristeigabriel** [comment]
daca doresti insa sa faci ceva de genul chestia asta ar trb sa ofere destul context

https://github.com/cristeigabriel/compiletime-string-to-bytearray/blob/main/compiletime-string-to-bytearray.cpp#L167
